package hdhnc;

import java.awt.Color;
import java.awt.Component;
import java.awt.FlowLayout;
import java.awt.GridLayout;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.io.File;
import java.text.DecimalFormat;
import javax.swing.Action;
import javax.swing.BorderFactory;
import javax.swing.DefaultCellEditor;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;

public class ScheduledJobs extends javax.swing.JFrame {
	JFileChooser jfcSource, jfcTarget;
	JComboBox jcbAction;

	/**
	 * Creates new form ScheduledJobs
	 */
	public ScheduledJobs() {
		super("ScheduledJobs");
		initComponents();
		setVisible(true);
		setLocationRelativeTo(null);
		// thiet lap jtable
		dataTable();

	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		bg = new javax.swing.ButtonGroup();
		jPanel1 = new javax.swing.JPanel();
		panlPath = new javax.swing.JPanel();
		jLbSource = new javax.swing.JLabel();
		jLbTarget = new javax.swing.JLabel();
		jtfSource = new javax.swing.JTextField();
		jtfTarget = new javax.swing.JTextField();
		jbtSource = new javax.swing.JButton();
		jbtTarget = new javax.swing.JButton();
		panlAED = new javax.swing.JPanel();
		jbAdd = new javax.swing.JButton();
		jbEdit = new javax.swing.JButton();
		jbDelete = new javax.swing.JButton();
		panlAction = new javax.swing.JPanel();
		jRbCopy = new javax.swing.JRadioButton();
		jRbDelete = new javax.swing.JRadioButton();
		jRbRemove = new javax.swing.JRadioButton();
		jScrollPane1 = new javax.swing.JScrollPane();
		jtData = new javax.swing.JTable();
		panlSetting = new javax.swing.JPanel();
		jCbGhiDe = new javax.swing.JCheckBox();
		jCbSendMail = new javax.swing.JCheckBox();
		jtfAddMail = new javax.swing.JTextField();
		jlbMail = new javax.swing.JLabel();
		jbtStart = new javax.swing.JButton();

		bg.add(jRbCopy);
		bg.add(jRbDelete);
		bg.add(jRbRemove);

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jLbSource.setText("Source");

		jLbTarget.setText("Target");

		jtfSource.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jtfSourceActionPerformed(evt);
			}
		});

		jbtSource.setText("...");
		jbtSource.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jbtSourceActionPerformed(evt);
			}
		});

		jbtTarget.setText("...");
		jbtTarget.setToolTipText("");
		jbtTarget.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jbtTargetActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout panlPathLayout = new javax.swing.GroupLayout(panlPath);
		panlPath.setLayout(panlPathLayout);
		panlPathLayout.setHorizontalGroup(panlPathLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(panlPathLayout.createSequentialGroup().addContainerGap()
						.addGroup(panlPathLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(jLbSource).addComponent(jLbTarget))
						.addGap(18, 18, 18)
						.addGroup(panlPathLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(jtfSource, javax.swing.GroupLayout.PREFERRED_SIZE, 225,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jtfTarget, javax.swing.GroupLayout.PREFERRED_SIZE, 225,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addGroup(panlPathLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(jbtTarget, javax.swing.GroupLayout.PREFERRED_SIZE, 35,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jbtSource, javax.swing.GroupLayout.PREFERRED_SIZE, 35,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
		panlPathLayout.setVerticalGroup(panlPathLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(panlPathLayout.createSequentialGroup().addContainerGap().addGroup(panlPathLayout
						.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
						.addGroup(panlPathLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLbSource).addComponent(jtfSource, javax.swing.GroupLayout.PREFERRED_SIZE,
										28, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addComponent(jbtSource))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addGroup(panlPathLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLbTarget)
								.addComponent(jtfTarget, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jbtTarget))
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

		panlPathLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] { jtfSource, jtfTarget });

		jbAdd.setText("Thêm");
		jbAdd.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jbAddActionPerformed(evt);
			}
		});

		jbEdit.setText("Sửa");
		jbEdit.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jbEditActionPerformed(evt);
			}
		});

		jbDelete.setText("Xóa");
		jbDelete.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jbDeleteActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout panlAEDLayout = new javax.swing.GroupLayout(panlAED);
		panlAED.setLayout(panlAEDLayout);
		panlAEDLayout.setHorizontalGroup(panlAEDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(panlAEDLayout.createSequentialGroup().addContainerGap()
						.addComponent(jbAdd, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(panlAEDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
								.addComponent(jbDelete, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(jbEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 63,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addContainerGap()));
		panlAEDLayout.setVerticalGroup(panlAEDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
						panlAEDLayout.createSequentialGroup().addContainerGap()
								.addGroup(panlAEDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
										.addComponent(jbAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 70,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGroup(panlAEDLayout.createSequentialGroup()
												.addComponent(jbEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 36,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addComponent(jbDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 28,
														javax.swing.GroupLayout.PREFERRED_SIZE)))
								.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

		panlAction.setBorder(javax.swing.BorderFactory.createTitledBorder("Action"));

		jRbCopy.setSelected(true);
		jRbCopy.setLabel("Copy");
		jRbCopy.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jRbCopyActionPerformed(evt);
			}
		});

		jRbDelete.setLabel("Delete");

		jRbRemove.setLabel("Remove");

		javax.swing.GroupLayout panlActionLayout = new javax.swing.GroupLayout(panlAction);
		panlAction.setLayout(panlActionLayout);
		panlActionLayout.setHorizontalGroup(panlActionLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(panlActionLayout.createSequentialGroup()
						.addGroup(panlActionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(jRbDelete).addComponent(jRbRemove).addComponent(jRbCopy))
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
		panlActionLayout
				.setVerticalGroup(panlActionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(panlActionLayout.createSequentialGroup().addComponent(jRbCopy)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(jRbDelete)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(jRbRemove)));

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup().addContainerGap(32, Short.MAX_VALUE)
						.addComponent(panlAction, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(panlPath, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(14, 14, 14)
						.addComponent(panlAED, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(26, 26, 26)));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup().addGroup(jPanel1Layout
						.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addComponent(panlAED, javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addGroup(jPanel1Layout.createSequentialGroup().addContainerGap()
								.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(panlPath, javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addComponent(panlAction, javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
						.addContainerGap()));

		jtData.setModel(
				new javax.swing.table.DefaultTableModel(
						new Object[][] { { null, null, null, null }, { null, null, null, null },
								{ null, null, null, null }, { null, null, null, null } },
						new String[] { "Title 1", "Title 2", "Title 3", "Title 4" }));
		jtData.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				jtDataMouseClicked(evt);
			}
		});
		jScrollPane1.setViewportView(jtData);

		panlSetting.setBorder(javax.swing.BorderFactory.createTitledBorder("Setting"));

		jCbGhiDe.setText("Ghi đè khi trùng");

		jCbSendMail.setText("Gửi mail khi hoàn thành");

		jtfAddMail.setText("");
		jtfAddMail.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jtfAddMailActionPerformed(evt);
			}
		});

		jlbMail.setText("tomcat@example.com");
		jlbMail.setForeground(Color.GRAY);

		javax.swing.GroupLayout panlSettingLayout = new javax.swing.GroupLayout(panlSetting);
		panlSetting.setLayout(panlSettingLayout);
		panlSettingLayout.setHorizontalGroup(panlSettingLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panlSettingLayout.createSequentialGroup()
						.addGap(0, 0, Short.MAX_VALUE)
						.addGroup(panlSettingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(jCbGhiDe)
								.addGroup(panlSettingLayout.createSequentialGroup().addComponent(jCbSendMail)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addGroup(
												panlSettingLayout
														.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(jlbMail, javax.swing.GroupLayout.PREFERRED_SIZE,
																158, javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jtfAddMail,
																javax.swing.GroupLayout.PREFERRED_SIZE, 158,
																javax.swing.GroupLayout.PREFERRED_SIZE))))
						.addGap(54, 54, 54)));
		panlSettingLayout.setVerticalGroup(panlSettingLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(panlSettingLayout.createSequentialGroup().addComponent(jCbGhiDe)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(panlSettingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jCbSendMail).addComponent(jtfAddMail,
										javax.swing.GroupLayout.PREFERRED_SIZE, 23,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
								javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addComponent(jlbMail).addContainerGap()));

		jbtStart.setText("Start");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE,
						javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
				.addGroup(layout.createSequentialGroup().addContainerGap().addGroup(layout
						.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(layout.createSequentialGroup()
								.addComponent(panlSetting, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addComponent(jbtStart, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addGap(8, 8, 8))
						.addComponent(jScrollPane1)).addContainerGap()));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
				.createSequentialGroup()
				.addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
						javax.swing.GroupLayout.PREFERRED_SIZE)
				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
				.addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 332,
						javax.swing.GroupLayout.PREFERRED_SIZE)
				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addComponent(panlSetting, javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addGroup(layout.createSequentialGroup().addGap(0, 0, Short.MAX_VALUE).addComponent(jbtStart,
								javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
				.addContainerGap()));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	// load data jtable - jtData
	private void dataTable() {
		ImageIcon test = new ImageIcon("D:\\check.png");
		model = new DefaultTableModel(new Object[] { "STT", "Name", "From", "To", "Action", "Size", "Status" }, 0);
		// model.insertRow(0, new Object[]{"1", "toan", jtfSource.getText(),
		// jtfTarget.getText(), "Chosser", sizeFile(jtfSource.getText()),
		// test});
		jtData.setModel(model);

		// khong cho nguoi dung thay doi thu tu cua cac cot bang cach
		// setReorderingAllowed thanh false
		jtData.getTableHeader().setReorderingAllowed(false);
		// kich thuoc cua tat ca cac cot se thay doi khi thay doi kich thuoc cua
		// 1 cot
		jtData.setAutoResizeMode(JTable.AUTO_RESIZE_ALL_COLUMNS);

		jtData.setEnabled(false);
		// thay doi kich thuoc cua cot mac dinh la 75px
		TableColumnModel tcm;
		tcm = jtData.getColumnModel();
		// thay doi cot STT thanh 20px
		tcm.getColumn(0).setPreferredWidth(20);
		// thay doi kich thuoc cot Status thanh 30
		tcm.getColumn(6).setPreferredWidth(30);

		// TAO COT jcheckbox
		String[] action = { "Copy", "Delete", "Remove" };
		JComboBox jbAction = new JComboBox(action);
		TableColumn col = jtData.getColumnModel().getColumn(4);
		col.setCellEditor(new DefaultCellEditor(jbAction));

	}

	// su ly su kien cho button Source
	private void jbtSourceActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jbtSourceActionPerformed
		jfcSource = new JFileChooser();
		jfcSource.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);
		if (jfcSource.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
			String fileName = jfcSource.getSelectedFile().getName();
			String dir = jfcSource.getCurrentDirectory().toString();
			jtfSource.setText(dir + "\\" + fileName);
			jtfSource.setEnabled(false);
		}

	}

	// su ly su kien cho button Target
	private void jbtTargetActionPerformed(java.awt.event.ActionEvent evt) {
		jfcTarget = new JFileChooser();
		jfcTarget.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);
		if (jfcTarget.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
			String fileName = jfcTarget.getSelectedFile().getName();
			String dir = jfcTarget.getCurrentDirectory().toString();
			jtfTarget.setText(dir + "\\" + fileName);
			jtfTarget.setEnabled(false);
		}

	}

	// su ly su kien cho button Add
	private void jbAddActionPerformed(java.awt.event.ActionEvent evt) {
		model.addRow(
				new Object[] { model.getRowCount() + 1, getFileFolderName(jtfSource.getText()), jtfSource.getText(),
						jtfTarget.getText(), "Chosser", convertSize(sizeFileOrFolder(jtfSource.getText())), "toan" });
		jtfSource.setText("");
		jtfTarget.setText("");
	}

	// su ly su kien cho radio button copy
	private void jRbCopyActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	// su ly su kien cho radio button remove
	private void jRbRemoveItemStateChanged(java.awt.event.ItemEvent evt) {
		jRbRemove.setOpaque(false);
		jRbRemove.addItemListener((ItemListener) this);
		this.getContentPane().add(jRbRemove);
		if (jRbRemove.isSelected()) {
			jbtStart.setBackground(Color.CYAN);
		}
	}

	// ????????????????
	private void jtfSourceActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void jtfAddMailActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	// xu ly su kien cho nut xoa
	private void jbDeleteActionPerformed(java.awt.event.ActionEvent evt) {
		int temp = jtData.getSelectedRow();
		if (temp >= 0) {
			model.removeRow(temp);
			// thu tu tu dong thay doi neu co 1 dong bi xoa
			for (int i = temp; i < jtData.getRowCount(); i++) {
				model.setValueAt(++temp, i, 0);
			}
		}
	}

	private void jbEditActionPerformed(java.awt.event.ActionEvent evt) {
		jtData.setEnabled(true);

	}

	private void jtDataMouseClicked(java.awt.event.MouseEvent evt) {
		if (jtData.isEnabled()) {
			jtfSource.setEnabled(true);
			jtfTarget.setEnabled(true);
			jtfSource.setText((String) jtData.getValueAt(jtData.getSelectedRow(), 2));
			jfcSource.setCurrentDirectory(new File("D:\\backup"));
			jtfTarget.setText((String) jtData.getValueAt(jtData.getSelectedRow(), 3));
		}
	}

	public static void main(String args[]) {
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(ScheduledJobs.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(ScheduledJobs.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(ScheduledJobs.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(ScheduledJobs.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		}
		// </editor-fold>
		try {// 10/03/16 10:25
			UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
		} catch (Exception e) {
			e.printStackTrace();
		}

		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new ScheduledJobs().setVisible(true);
			}
		});
	}

	// tinh kich thuoc file
	public double sizeFile(File file) {
		double size;
		// return file.length();
		double bytes = file.length();
		if (bytes <= 1024) {
			size = 1;
		} else {
			size = bytes / 1024;
		}
		return size;
	}

	// tinh kich thuoc folder
	private double sizeFolder(File directory) {
		double length = 0;
		for (File file : directory.listFiles()) {
			if (file.isFile()) {
				length += file.length();
			} else {
				length += sizeFolder(file);
			}
		}
		return length;
	}

	// kiem tra duong dan da cho la file hay folder de dua ra cach tinh size
	// dung
	private double sizeFileOrFolder(String path) {
		File file = new File(path);
		if (file.exists()) {
			if (file.isFile())
				return sizeFile(file);
			else
				return sizeFolder(file);
		} else
			return 0;
	}

	private String convertSize(double size) {
		// hien thi phan cach so hang ngan bang dau phay
		DecimalFormat df = new DecimalFormat("#,###");
		String dx = df.format(size) + " KB";
		return dx;
	}

	private String getFileFolderName(String path) {
		File file = new File(path);
		String name = null;
		if (file.exists()) {
			if (file.isFile()) {
				name = file.getName();
			} else {
				name = file.getName();
			}
		}
		return name;
	}

	public static void moveFF(File oldpathFF) {
		// kiem tra coi duong dan co phai la thu muc do co rong hay ko
		if (oldpathFF.isDirectory()) {
			String[] files = oldpathFF.list();
			// neu rong thi thuc hien move
			if (files.length < 0) {
				try {
					if (oldpathFF
							.renameTo(new File("C:\\Users\\thang\\Desktop\\files\\files2\\" + oldpathFF.getName()))) {
						System.out.println("The Forder was moved successfully to the new folder");
					} else {
						System.out.println("The Forder was not moved.");
					}
				} catch (Exception e) {
					e.printStackTrace();
				}
			} else {
				// khong rong thi dung
				System.out.println("The Forder is not empty!");
			}
		}
		// kiem tra coi neu duong dan khong phai thu muc
		else if (!oldpathFF.isDirectory()) {
			try {
				if (oldpathFF.renameTo(new File("C:\\Users\\thang\\Desktop\\files\\files2\\" + oldpathFF.getName()))) {
					System.out.println("The file was moved successfully to the new folder");
				} else {
					System.out.println("The File was not moved.");
				}
			} catch (Exception e) {
				e.printStackTrace();
			}
		}
	}

	private DefaultTableModel model;
	private javax.swing.ButtonGroup bg;
	private javax.swing.JCheckBox jCbGhiDe;
	private javax.swing.JCheckBox jCbSendMail;
	private javax.swing.JLabel jLbSource;
	private javax.swing.JLabel jLbTarget;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JRadioButton jRbCopy;
	private javax.swing.JRadioButton jRbDelete;
	private javax.swing.JRadioButton jRbRemove;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JButton jbAdd;
	private javax.swing.JButton jbDelete;
	private javax.swing.JButton jbEdit;
	private javax.swing.JButton jbtSource;
	private javax.swing.JButton jbtStart;
	private javax.swing.JButton jbtTarget;
	private javax.swing.JLabel jlbMail;
	public javax.swing.JTable jtData;
	private javax.swing.JTextField jtfAddMail;
	private javax.swing.JTextField jtfSource;
	private javax.swing.JTextField jtfTarget;
	private javax.swing.JPanel panlAED;
	private javax.swing.JPanel panlAction;
	private javax.swing.JPanel panlPath;
	private javax.swing.JPanel panlSetting;
}
