/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.37
 * Generated at: 2018-05-10 08:21:27 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class DonHang_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("//Menu.jsp", Long.valueOf(1525940476604L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<meta name=\"description\" content=\"\">\r\n");
      out.write("<meta name=\"author\" content=\"\">\r\n");
      out.write("\r\n");
      out.write("<title>Đơn hàng</title>\r\n");
      out.write("\r\n");
      out.write("<!-- Bootstrap Core CSS -->\r\n");
      out.write("<link href=\"css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<!-- Custom CSS -->\r\n");
      out.write("<link href=\"css/sb-admin.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<!-- Custom Fonts -->\r\n");
      out.write("<link href=\"font-awesome-4.1.0/css/font-awesome.min.css\"\r\n");
      out.write("\trel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("\r\n");
      out.write("<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->\r\n");
      out.write("<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->\r\n");
      out.write("<!--[if lt IE 9]>\r\n");
      out.write("        <script src=\"https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js\"></script>\r\n");
      out.write("        <script src=\"https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js\"></script>\r\n");
      out.write("    <![endif]-->\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t<div id=\"wrapper\">\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- Navigation -->\r\n");
      out.write("\t\t");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div>\r\n");
      out.write("\t\t<nav class=\"navbar navbar-inverse navbar-fixed-top\" role=\"navigation\">\r\n");
      out.write("\t\t<!-- Brand and toggle get grouped for better mobile display -->\r\n");
      out.write("\t\t<div class=\"navbar-header\">\r\n");
      out.write("\t\t\t<button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\"\r\n");
      out.write("\t\t\t\tdata-target=\".navbar-ex1-collapse\">\r\n");
      out.write("\t\t\t\t<span class=\"sr-only\">Toggle navigation</span> <span\r\n");
      out.write("\t\t\t\t\tclass=\"icon-bar\"></span> <span class=\"icon-bar\"></span> <span\r\n");
      out.write("\t\t\t\t\tclass=\"icon-bar\"></span>\r\n");
      out.write("\t\t\t</button>\r\n");
      out.write("\t\t\t<a class=\"navbar-brand\" href=\"index.html\">TK Shop Admin</a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- Top Menu Items -->\r\n");
      out.write("\t\t<ul class=\"nav navbar-right top-nav\">\r\n");
      out.write("\t\t\t<li class=\"dropdown\"><a href=\"#\" class=\"dropdown-toggle\"\r\n");
      out.write("\t\t\t\tdata-toggle=\"dropdown\"><i class=\"fa fa-envelope\"></i> <b\r\n");
      out.write("\t\t\t\t\tclass=\"caret\"></b></a>\r\n");
      out.write("\t\t\t\t<ul class=\"dropdown-menu message-dropdown\">\r\n");
      out.write("\t\t\t\t\t<li class=\"message-preview\"><a href=\"#\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"media\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"pull-left\"> <img class=\"media-object\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tsrc=\"E:\\Admin-SB-v2\\SB-Admin-2-master\\img\\sms.png\" alt=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"media-body\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<h5 class=\"media-heading\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<strong>Hoàng Vũ</strong>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</h5>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p class=\"small text-muted\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<i class=\"fa fa-clock-o\"></i> Hôm qua lúc 4:32 PM\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p>Hôm qua bạn có một tin nhắn từ...</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"message-preview\"><a href=\"#\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"media\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"pull-left\"> <img class=\"media-object\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tsrc=\"E:\\Admin-SB-v2\\SB-Admin-2-master\\img\\sms.png\" alt=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"media-body\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<h5 class=\"media-heading\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<strong>Hoàng Vũ</strong>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</h5>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p class=\"small text-muted\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<i class=\"fa fa-clock-o\"></i> Hôm qua lúc 4:32 PM\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p>Hôm qua bạn có một tin nhắn từ...</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"message-preview\"><a href=\"#\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"media\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"pull-left\"> <img class=\"media-object\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tsrc=\"E:\\Admin-SB-v2\\SB-Admin-2-master\\img\\sms.png\" alt=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"media-body\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<h5 class=\"media-heading\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<strong>Hoàng Vũ</strong>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</h5>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p class=\"small text-muted\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<i class=\"fa fa-clock-o\"></i> Hôm qua lúc 4:32 PM\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p>Hôm qua bạn có một tin nhắn từ từ...</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"message-footer\"><a href=\"#\">Xem tất cả tin nhắn</a>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t<li class=\"dropdown\"><a href=\"#\" class=\"dropdown-toggle\"\r\n");
      out.write("\t\t\t\tdata-toggle=\"dropdown\"><i class=\"fa fa-bell\"></i> <b\r\n");
      out.write("\t\t\t\t\tclass=\"caret\"></b></a>\r\n");
      out.write("\t\t\t\t<ul class=\"dropdown-menu alert-dropdown\">\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">Bạn có đơn hàng từ <span\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"label label-default\">Alert Badge</span></a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">Bạn có đơn hàng từ <span\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"label label-primary\">Alert Badge</span></a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">Bạn có đơn hàng từ <span\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"label label-success\">Alert Badge</span></a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">Bạn có đơn hàng từ <span\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"label label-info\">Alert Badge</span></a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">Bạn có đơn hàng từ <span\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"label label-warning\">Alert Badge</span></a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">Bạn có đơn hàng từ <span\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"label label-danger\">Alert Badge</span></a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"divider\"></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">Xem tất cả</a></li>\r\n");
      out.write("\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t<li class=\"dropdown\"><a href=\"#\" class=\"dropdown-toggle\"\r\n");
      out.write("\t\t\t\tdata-toggle=\"dropdown\"><i class=\"fa fa-user\"></i> Hoàng Vũ <b\r\n");
      out.write("\t\t\t\t\tclass=\"caret\"></b></a>\r\n");
      out.write("\t\t\t\t<ul class=\"dropdown-menu\">\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\"><i class=\"fa fa-fw fa-user\"></i> Trang cá\r\n");
      out.write("\t\t\t\t\t\t\tnhân</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\"><i class=\"fa fa-fw fa-envelope\"></i> Hộp\r\n");
      out.write("\t\t\t\t\t\t\tthư</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\"><i class=\"fa fa-fw fa-gear\"></i> Cài đặt</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"divider\"></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\"><i class=\"fa fa-fw fa-power-off\"></i> Đăng\r\n");
      out.write("\t\t\t\t\t\t\txuất</a></li>\r\n");
      out.write("\t\t\t\t</ul></li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t\t<!-- Sidebar Menu Items - These collapse to the responsive navigation menu on small screens -->\r\n");
      out.write("\t\t<div class=\"collapse navbar-collapse navbar-ex1-collapse\">\r\n");
      out.write("\t\t\t<ul class=\"nav navbar-nav side-nav\">\r\n");
      out.write("\t\t\t\t<li><a href=\"index.jsp\"><i class=\"fa fa-fw fa-dashboard\"></i>\r\n");
      out.write("\t\t\t\t\t\tTổng quan</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"charts.html\"><i\r\n");
      out.write("\t\t\t\t\t\tclass=\"fa fa-fw fa-bar-chart-o\"></i> Thống kê chi tiết</a></li>\r\n");
      out.write("\t\t\t\t<li class=\"active\"><a href=\"tables.html\"><i\r\n");
      out.write("\t\t\t\t\t\tclass=\"fa fa-fw fa-table\"></i> Đơn hàng</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"forms.html\"><i class=\"fa fa-fw fa-table\"></i>\r\n");
      out.write("\t\t\t\t\t\tKhách hàng</a></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<li><a href=\"javascript:;\" data-toggle=\"collapse\"\r\n");
      out.write("\t\t\t\t\tdata-target=\"#demo\"><i class=\"fa fa-fw fa-table\"></i> Sản Phẩm\r\n");
      out.write("\t\t\t\t\t\t<i class=\"fa fa-fw fa-caret-down\"></i></a>\r\n");
      out.write("\t\t\t\t\t<ul id=\"demo\" class=\"collapse\">\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"quan-ly-sp.html\">Tổng quan</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"them-sp.html\">Thêm sản phẩm mới</a></li>\r\n");
      out.write("\t\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"bootstrap-grid.html\"><i\r\n");
      out.write("\t\t\t\t\t\tclass=\"fa fa-fw fa-wrench\"></i> Cài đặt</a></li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- /.navbar-collapse --> </nav>\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div id=\"page-wrapper\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"container-fluid\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!-- Page Heading -->\r\n");
      out.write("\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col-lg-12\">\r\n");
      out.write("\t\t\t\t\t\t<h1 class=\"page-header\">Thống kê đơn hàng</h1>\r\n");
      out.write("\t\t\t\t\t\t<ol class=\"breadcrumb\">\r\n");
      out.write("\t\t\t\t\t\t\t<li><i class=\"fa fa-dashboard\"></i> <a href=\"index.html\">Tổng\r\n");
      out.write("\t\t\t\t\t\t\t\t\tquan</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"active\"><i class=\"fa fa-table\"></i> Đơn hàng</li>\r\n");
      out.write("\t\t\t\t\t\t</ol>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t<center>\r\n");
      out.write("\t\t\t\t\t\t<h3>Hành động</h3>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"them-sp.html\"><input type=button value=\"Thêm\"></a>\r\n");
      out.write("\t\t\t\t\t\t<input type=button value=\"Chỉnh sửa\"> <input type=button\r\n");
      out.write("\t\t\t\t\t\t\tvalue=\"Xóa\">\r\n");
      out.write("\t\t\t\t\t</center>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t<!-- Table Don hang -->\r\n");
      out.write("\t\t\t\t<div class=\"table-responsive\">\r\n");
      out.write("\t\t\t\t\t<table class=\"table table-bordered table-hover\">\r\n");
      out.write("\t\t\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th><input type=\"checkbox\" value=\"\"></th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th>STT</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th>ID sản phẩm</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th>Tên sản phẩm</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th>Đơn giá</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th>Số lượng</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th>Mô tả</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- <th>Nhà sản xuất</th> -->\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><input type=\"checkbox\" value=\"\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>SP0001</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>TN0001</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>Bàn tròn xoay inox</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>629.000 VNĐ</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>10</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>Sản phẩm mới được gia công thủ công....</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- <td>Co.ltd Group 12 MIS </td> -->\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><input type=\"checkbox\" value=\"\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>SP0001</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>PA Grace1</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>Ghế Grace 1</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>190.000 VNĐ</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>19</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>Sản phẩm nội thất căn hộ mới gia công....</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- <td>Ghế</td> -->\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><input type=\"checkbox\" value=\"\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>SP0001</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>TN0001</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>Bàn tròn xoay inox</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>629.000 VNĐ</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>10</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>Sản phẩm mới được gia công thủ công....</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- <td>Bàn</td> -->\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><input type=\"checkbox\" value=\"\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>SP0001</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>PA Grace1</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>Ghế Grace 1</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>190.000 VNĐ</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>19</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>Sản phẩm nội thất căn hộ mới gia công....</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- <td>Ghế</td> -->\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><input type=\"checkbox\" value=\"\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>SP0001</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>TN0001</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>Bàn tròn xoay inox</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>629.000 VNĐ</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>10</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>Sản phẩm mới được gia công thủ công....</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- <td>Bàn</td> -->\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><input type=\"checkbox\" value=\"\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>SP0001</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>PA Grace1</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>Ghế Grace 1</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>190.000 VNĐ</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>19</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>Sản phẩm nội thất căn hộ mới gia công....</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- <td>Ghế</td> -->\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><input type=\"checkbox\" value=\"\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>SP0001</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>TN0001</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>Bàn tròn xoay inox</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>629.000 VNĐ</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>10</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>Sản phẩm mới được gia công thủ công....</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- <td>Bàn</td> -->\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><input type=\"checkbox\" value=\"\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>SP0001</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>PA Grace1</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>Ghế Grace 1</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>190.000 VNĐ</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>19</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>Sản phẩm nội thất căn hộ mới gia công....</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- <td>Ghế</td> -->\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><input type=\"checkbox\" value=\"\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>SP0001</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>TN0001</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>Bàn tròn xoay inox</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>629.000 VNĐ</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>10</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>Sản phẩm mới được gia công thủ công....</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- <td>Bàn</td> -->\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><input type=\"checkbox\" value=\"\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>SP0001</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>PA Grace1</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>Ghế Grace 1</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>190.000 VNĐ</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>19</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>Sản phẩm nội thất căn hộ mới gia công....</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- <td>Ghế</td> -->\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><input type=\"checkbox\" value=\"\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>SP0001</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>TN0001</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>Bàn tròn xoay inox</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>629.000 VNĐ</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>10</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>Sản phẩm mới được gia công thủ công....</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- <td>Bàn</td> -->\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><input type=\"checkbox\" value=\"\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>SP0001</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>PA Grace1</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>Ghế Grace 1</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>190.000 VNĐ</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>19</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>Sản phẩm nội thất căn hộ mới gia công....</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- <td>Ghế</td> -->\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><input type=\"checkbox\" value=\"\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>SP0001</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>TN0001</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>Bàn tròn xoay inox</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>629.000 VNĐ</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>10</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>Sản phẩm mới được gia công thủ công....</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- <td>Bàn</td> -->\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><input type=\"checkbox\" value=\"\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>SP0001</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>PA Grace1</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>Ghế Grace 1</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>190.000 VNĐ</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>19</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>Sản phẩm nội thất căn hộ mới gia công....</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- <td>Ghế</td> -->\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><input type=\"checkbox\" value=\"\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>SP0001</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>TN0001</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>Bàn tròn xoay inox</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>629.000 VNĐ</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>10</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>Sản phẩm mới được gia công thủ công....</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- <td>Bàn</td> -->\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><input type=\"checkbox\" value=\"\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>SP0001</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>PA Grace1</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>Ghế Grace 1</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>190.000 VNĐ</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>19</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>Sản phẩm nội thất căn hộ mới gia công....</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- <td>Ghế</td> -->\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!-- /.row -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t<!-- /.row -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col-lg-6\">\r\n");
      out.write("\t\t\t\t\t\t<h2>Thống kê theo ngày</h2>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"table-responsive\">\r\n");
      out.write("\t\t\t\t\t\t\t<table class=\"table table-bordered table-hover\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th>Loại mặt hàng</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th>Lượng truy cập</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th>% Lượng truy cập mới</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th>Doanh thu</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>Ghế</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>1265</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>32.3%</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>650.000 VNĐ</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>Bàn</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>261</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>33.3%</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>150.000 VNĐ</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>Tủ</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>665</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>21.3%</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>320.000 VNĐ</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>Giá treo</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>9516</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>89.3%</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>1.500.000 VNĐ</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>Kệ xếp</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>230</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>34.3%</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>250.000 VNĐ</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>Cửa</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>421</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>60.3%</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>350.000 VNĐ</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>Kính</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>1233</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>93.2%</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>950.000 VNĐ</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-lg-6\">\r\n");
      out.write("\t\t\t\t\t\t<h2>Thống kê theo tháng</h2>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"table-responsive\">\r\n");
      out.write("\t\t\t\t\t\t\t<table class=\"table table-bordered table-hover\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th>Loại mặt hàng</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th>Lượng truy cập</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th>% Lượng truy cập mới</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th>Doanh thu</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>Ghế</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>1265</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>32.3%</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>650.000 VNĐ</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>Bàn</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>261</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>33.3%</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>150.000 VNĐ</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>Tủ</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>665</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>21.3%</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>320.000 VNĐ</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>Giá treo</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>9516</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>89.3%</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>1.500.000 VNĐ</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>Kệ xếp</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>230</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>34.3%</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>250.000 VNĐ</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>Cửa</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>421</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>60.3%</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>350.000 VNĐ</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>Kính</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>1233</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>93.2%</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>950.000 VNĐ</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!-- /.row -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!-- /.row -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col-lg-6\">\r\n");
      out.write("\t\t\t\t\t\t<h2>Thống kê theo năm</h2>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"table-responsive\">\r\n");
      out.write("\t\t\t\t\t\t\t<table class=\"table table-bordered table-hover table-striped\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th>Loại mặt hàng</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th>Lượng truy cập</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th>% Lượng truy cập mới</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th>Doanh thu</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr class=\"active\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>Ghế</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>1265</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>32.3%</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>650.000 VNĐ</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr class=\"success\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>Bàn</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>261</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>33.3%</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>150.000 VNĐ</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr class=\"warning\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>Tủ</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>665</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>21.3%</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>320.000 VNĐ</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr class=\"danger\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>Giá treo</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>9516</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>89.3%</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>1.500.000 VNĐ</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>Kệ xếp</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>230</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>34.3%</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>250.000 VNĐ</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>Cửa</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>421</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>60.3%</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>350.000 VNĐ</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>Kính</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>1233</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>93.2%</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>950.000 VNĐ</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!-- /.row -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- /.container-fluid -->\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- /#page-wrapper -->\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- /#wrapper -->\r\n");
      out.write("\r\n");
      out.write("\t<!-- jQuery Version 1.11.0 -->\r\n");
      out.write("\t<script src=\"js/jquery-1.11.0.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t<!-- Bootstrap Core JavaScript -->\r\n");
      out.write("\t<script src=\"js/bootstrap.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
