/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.37
 * Generated at: 2018-05-10 08:32:59 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class KhachHang_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("    <meta name=\"description\" content=\"\">\r\n");
      out.write("    <meta name=\"author\" content=\"\">\r\n");
      out.write("\r\n");
      out.write("    <title>Khách hàng</title>\r\n");
      out.write("\r\n");
      out.write("    <!-- Bootstrap Core CSS -->\r\n");
      out.write("    <link href=\"css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Custom CSS -->\r\n");
      out.write("    <link href=\"css/sb-admin.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Custom Fonts -->\r\n");
      out.write("    <link href=\"font-awesome-4.1.0/css/font-awesome.min.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("\r\n");
      out.write("    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->\r\n");
      out.write("    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->\r\n");
      out.write("    <!--[if lt IE 9]>\r\n");
      out.write("        <script src=\"https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js\"></script>\r\n");
      out.write("        <script src=\"https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js\"></script>\r\n");
      out.write("    <![endif]-->\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("    <div id=\"wrapper\">\r\n");
      out.write("\r\n");
      out.write("        <!-- Navigation -->\r\n");
      out.write("        <nav class=\"navbar navbar-inverse navbar-fixed-top\" role=\"navigation\">\r\n");
      out.write("            <!-- Brand and toggle get grouped for better mobile display -->\r\n");
      out.write("            <div class=\"navbar-header\">\r\n");
      out.write("                <button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\" data-target=\".navbar-ex1-collapse\">\r\n");
      out.write("                    <span class=\"sr-only\">Toggle navigation</span>\r\n");
      out.write("                    <span class=\"icon-bar\"></span>\r\n");
      out.write("                    <span class=\"icon-bar\"></span>\r\n");
      out.write("                    <span class=\"icon-bar\"></span>\r\n");
      out.write("                </button>\r\n");
      out.write("                <a class=\"navbar-brand\" href=\"index.html\">TK Shop Admin</a>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- Top Menu Items -->\r\n");
      out.write("           <ul class=\"nav navbar-right top-nav\">\r\n");
      out.write("                <li class=\"dropdown\">\r\n");
      out.write("                    <a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\"><i class=\"fa fa-envelope\"></i> <b class=\"caret\"></b></a>\r\n");
      out.write("                    <ul class=\"dropdown-menu message-dropdown\">\r\n");
      out.write("                        <li class=\"message-preview\">\r\n");
      out.write("                            <a href=\"#\">\r\n");
      out.write("                                <div class=\"media\">\r\n");
      out.write("                                    <span class=\"pull-left\">\r\n");
      out.write("                                        <img class=\"media-object\" src=\"E:\\Admin-SB-v2\\SB-Admin-2-master\\img\\sms.png\" alt=\"\">\r\n");
      out.write("                                    </span>\r\n");
      out.write("                                    <div class=\"media-body\">\r\n");
      out.write("                                        <h5 class=\"media-heading\"><strong>Hoàng Vũ</strong>\r\n");
      out.write("                                        </h5>\r\n");
      out.write("                                        <p class=\"small text-muted\"><i class=\"fa fa-clock-o\"></i> Hôm qua lúc 4:32 PM</p>\r\n");
      out.write("                                        <p>Hôm qua bạn có một tin nhắn từ...</p>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"message-preview\">\r\n");
      out.write("                            <a href=\"#\">\r\n");
      out.write("                                <div class=\"media\">\r\n");
      out.write("                                    <span class=\"pull-left\">\r\n");
      out.write("                                        <img class=\"media-object\" src=\"E:\\Admin-SB-v2\\SB-Admin-2-master\\img\\sms.png\" alt=\"\">\r\n");
      out.write("                                    </span>\r\n");
      out.write("                                    <div class=\"media-body\">\r\n");
      out.write("                                        <h5 class=\"media-heading\"><strong>Hoàng Vũ</strong>\r\n");
      out.write("                                        </h5>\r\n");
      out.write("                                        <p class=\"small text-muted\"><i class=\"fa fa-clock-o\"></i> Hôm qua lúc 4:32 PM</p>\r\n");
      out.write("                                        <p>Hôm qua bạn có một tin nhắn từ...</p>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"message-preview\">\r\n");
      out.write("                            <a href=\"#\">\r\n");
      out.write("                                <div class=\"media\">\r\n");
      out.write("                                    <span class=\"pull-left\">\r\n");
      out.write("                                        <img class=\"media-object\" src=\"E:\\Admin-SB-v2\\SB-Admin-2-master\\img\\sms.png\" alt=\"\">\r\n");
      out.write("                                    </span>\r\n");
      out.write("                                    <div class=\"media-body\">\r\n");
      out.write("                                        <h5 class=\"media-heading\"><strong>Hoàng Vũ</strong>\r\n");
      out.write("                                        </h5>\r\n");
      out.write("                                        <p class=\"small text-muted\"><i class=\"fa fa-clock-o\"></i> Hôm qua lúc 4:32 PM</p>\r\n");
      out.write("                                        <p>Hôm qua bạn có một tin nhắn từ từ...</p>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"message-footer\">\r\n");
      out.write("                            <a href=\"#\">Xem tất cả tin nhắn</a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"dropdown\">\r\n");
      out.write("                    <a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\"><i class=\"fa fa-bell\"></i> <b class=\"caret\"></b></a>\r\n");
      out.write("                    <ul class=\"dropdown-menu alert-dropdown\">\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <a href=\"#\">Bạn có đơn hàng từ <span class=\"label label-default\">Alert Badge</span></a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <a href=\"#\">Bạn có đơn hàng từ <span class=\"label label-primary\">Alert Badge</span></a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <a href=\"#\">Bạn có đơn hàng từ <span class=\"label label-success\">Alert Badge</span></a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <a href=\"#\">Bạn có đơn hàng từ <span class=\"label label-info\">Alert Badge</span></a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <a href=\"#\">Bạn có đơn hàng từ <span class=\"label label-warning\">Alert Badge</span></a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <a href=\"#\">Bạn có đơn hàng từ <span class=\"label label-danger\">Alert Badge</span></a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"divider\"></li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <a href=\"#\">Xem tất cả</a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"dropdown\">\r\n");
      out.write("                    <a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\"><i class=\"fa fa-user\"></i> Hoàng Vũ <b class=\"caret\"></b></a>\r\n");
      out.write("                    <ul class=\"dropdown-menu\">\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <a href=\"#\"><i class=\"fa fa-fw fa-user\"></i> Trang cá nhân</a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <a href=\"#\"><i class=\"fa fa-fw fa-envelope\"></i> Hộp thư</a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <a href=\"#\"><i class=\"fa fa-fw fa-gear\"></i> Cài đặt</a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"divider\"></li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <a href=\"#\"><i class=\"fa fa-fw fa-power-off\"></i> Đăng xuất</a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("            <!-- Sidebar Menu Items - These collapse to the responsive navigation menu on small screens -->\r\n");
      out.write("            <div class=\"collapse navbar-collapse navbar-ex1-collapse\">\r\n");
      out.write("                <ul class=\"nav navbar-nav side-nav\">\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a href=\"index.html\"><i class=\"fa fa-fw fa-dashboard\"></i> Tổng quan</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a href=\"charts.html\"><i class=\"fa fa-fw fa-bar-chart-o\"></i> Thống kê chi tiết</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a href=\"tables.html\"><i class=\"fa fa-fw fa-table\"></i> Đơn hàng</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"active\">\r\n");
      out.write("                        <a href=\"forms.html\"><i class=\"fa fa-fw fa-table\"></i> Khách hàng</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    \r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a href=\"javascript:;\" data-toggle=\"collapse\" data-target=\"#demo\"><i class=\"fa fa-fw fa-table\"></i> Sản Phẩm <i class=\"fa fa-fw fa-caret-down\"></i></a>\r\n");
      out.write("                        <ul id=\"demo\" class=\"collapse\">\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a href=\"quan-ly-sp.html\">Tổng quan</a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a href=\"them-sp.html\">Thêm sản phẩm mới</a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("\t\t\t\t\t<li>\r\n");
      out.write("                        <a href=\"bootstrap-grid.html\"><i class=\"fa fa-fw fa-wrench\"></i> Cài đặt</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- /.navbar-collapse -->\r\n");
      out.write("        </nav>\r\n");
      out.write("\r\n");
      out.write("        <div id=\"page-wrapper\">\r\n");
      out.write("\r\n");
      out.write("            <div class=\"container-fluid\">\r\n");
      out.write("\r\n");
      out.write("                <!-- Page Heading -->\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <div class=\"col-lg-12\">\r\n");
      out.write("                        <h1 class=\"page-header\">\r\n");
      out.write("                            Quản lý khách hàng\r\n");
      out.write("                        </h1>\r\n");
      out.write("                        <ol class=\"breadcrumb\">\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <i class=\"fa fa-dashboard\"></i>  <a href=\"index.html\">Tổng quan</a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li class=\"active\">\r\n");
      out.write("                                <i class=\"fa fa-edit\"></i> Khách hàng\r\n");
      out.write("                            </li>\r\n");
      out.write("                        </ol>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <!-- /.row -->\r\n");
      out.write("\t\t\t\t<div class=\"table-responsive\">\r\n");
      out.write("                            <table class=\"table table-bordered table-hover\">\r\n");
      out.write("                                <thead>\r\n");
      out.write("                                    <tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th>STT</th>\r\n");
      out.write("                                        <th>Họ và tên</th>\r\n");
      out.write("                                        <th>Giới tính</th>\r\n");
      out.write("                                        <th>Số điện thoại</th>\r\n");
      out.write("                                        <th>Địa chỉ</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th>Email</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th>Trạng thái</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th>Hành động</th>\r\n");
      out.write("                                    </tr>\r\n");
      out.write("                                </thead>\r\n");
      out.write("                                <tbody>\r\n");
      out.write("                                    <tr>\r\n");
      out.write("                                        <td>KH0001</td>\r\n");
      out.write("                                        <td>Hoàng Đức Thắng</td>\r\n");
      out.write("                                        <td>Nam</td>\r\n");
      out.write("                                        <td>01653987445</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>123 Khu phố 6 - Linh Trung - Thủ Đức - HCM</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>thanghoang@gmail.com</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>Đang hoạt động</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td><input type=button value = \"Gửi mail cảnh báo\"></td>\r\n");
      out.write("                                    </tr>\r\n");
      out.write("                                    <tr>\r\n");
      out.write("                                        <td>KH0001</td>\r\n");
      out.write("                                        <td>Ngô Văn Khương</td>\r\n");
      out.write("                                        <td>Nam</td>\r\n");
      out.write("                                        <td>01653987445</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>123 Khu phố 6 - Linh Trung - Thủ Đức - HCM</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>khuongngo@gmail.com</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>Đang hoạt động</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td><input type=button value = \"Gửi mail cảnh báo\"></td>\r\n");
      out.write("                                    </tr>\r\n");
      out.write("                                    <tr>\r\n");
      out.write("                                        <td>KH0001</td>\r\n");
      out.write("                                        <td>Phan Khả Khắt</td>\r\n");
      out.write("                                        <td>Nam</td>\r\n");
      out.write("                                        <td>01653987445</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>123 Khu phố 6 - Linh Trung - Thủ Đức - HCM</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>khatphan@gmail.com</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>Đang hoạt động</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td><input type=button value = \"Gửi mail cảnh báo\"></td>\r\n");
      out.write("                                    </tr>\r\n");
      out.write("                                    <tr>\r\n");
      out.write("                                        <td>KH0001</td>\r\n");
      out.write("                                        <td>Vũ Như Chương</td>\r\n");
      out.write("                                        <td>Nam</td>\r\n");
      out.write("                                        <td>01653987445</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>123 Khu phố 6 - Linh Trung - Thủ Đức - HCM</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>chuongvu@gmail.com</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>Đang hoạt động</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td><input type=button value = \"Gửi mail cảnh báo\"></td>\r\n");
      out.write("                                    </tr>\r\n");
      out.write("                                    <tr>\r\n");
      out.write("                                        <td>KH0001</td>\r\n");
      out.write("                                        <td>Võ Sỹ Bình</td>\r\n");
      out.write("                                        <td>Nữ</td>\r\n");
      out.write("                                        <td>01653987445</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>123 Khu phố 6 - Linh Trung - Thủ Đức - HCM</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>binhvo@gmail.com</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>Đang hoạt động</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td><input type=button value = \"Gửi mail cảnh báo\"></td>\r\n");
      out.write("                                    </tr>\r\n");
      out.write("                                    <tr>\r\n");
      out.write("                                        <td>KH0001</td>\r\n");
      out.write("                                        <td>Khương Hải Châu</td>\r\n");
      out.write("                                        <td>Nữ</td>\r\n");
      out.write("                                        <td>01653987445</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>123 Khu phố 6 - Linh Trung - Thủ Đức - HCM</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>khuonghaichau@gmail.com</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>Đang hoạt động</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td><input type=button value = \"Gửi mail cảnh báo\"></td>\r\n");
      out.write("                                    </tr>\r\n");
      out.write("                                    <tr>\r\n");
      out.write("                                        <td>KH0001</td>\r\n");
      out.write("                                        <td>Khương Hải Châu</td>\r\n");
      out.write("                                        <td>Nữ</td>\r\n");
      out.write("                                        <td>01653987445</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>123 Khu phố 6 - Linh Trung - Thủ Đức - HCM</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>khuonghaichau@gmail.com</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>Đang hoạt động</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td><input type=button value = \"Gửi mail cảnh báo\"></td>\r\n");
      out.write("                                    </tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("                                        <td>KH0001</td>\r\n");
      out.write("                                        <td>Khương Hải Châu</td>\r\n");
      out.write("                                        <td>Nữ</td>\r\n");
      out.write("                                        <td>01653987445</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>123 Khu phố 6 - Linh Trung - Thủ Đức - HCM</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>khuonghaichau@gmail.com</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>Đang hoạt động</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td><input type=button value = \"Gửi mail cảnh báo\"></td>\r\n");
      out.write("                                    </tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("                                        <td>KH0001</td>\r\n");
      out.write("                                        <td>Khương Hải Châu</td>\r\n");
      out.write("                                        <td>Nữ</td>\r\n");
      out.write("                                        <td>01653987445</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>123 Khu phố 6 - Linh Trung - Thủ Đức - HCM</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>khuonghaichau@gmail.com</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>Đang hoạt động</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td><input type=button value = \"Gửi mail cảnh báo\"></td>\r\n");
      out.write("                                    </tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("                                        <td>KH0001</td>\r\n");
      out.write("                                        <td>Khương Hải Châu</td>\r\n");
      out.write("                                        <td>Nữ</td>\r\n");
      out.write("                                        <td>01653987445</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>123 Khu phố 6 - Linh Trung - Thủ Đức - HCM</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>khuonghaichau@gmail.com</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>Đang hoạt động</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td><input type=button value = \"Gửi mail cảnh báo\"></td>\r\n");
      out.write("                                    </tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("                                        <td>KH0001</td>\r\n");
      out.write("                                        <td>Khương Hải Châu</td>\r\n");
      out.write("                                        <td>Nữ</td>\r\n");
      out.write("                                        <td>01653987445</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>123 Khu phố 6 - Linh Trung - Thủ Đức - HCM</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>khuonghaichau@gmail.com</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>Đang hoạt động</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td><input type=button value = \"Gửi mail cảnh báo\"></td>\r\n");
      out.write("                                    </tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("                                        <td>KH0001</td>\r\n");
      out.write("                                        <td>Khương Hải Châu</td>\r\n");
      out.write("                                        <td>Nữ</td>\r\n");
      out.write("                                        <td>01653987445</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>123 Khu phố 6 - Linh Trung - Thủ Đức - HCM</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>khuonghaichau@gmail.com</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>Đang hoạt động</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td><input type=button value = \"Gửi mail cảnh báo\"></td>\r\n");
      out.write("                                    </tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("                                        <td>KH0001</td>\r\n");
      out.write("                                        <td>Khương Hải Châu</td>\r\n");
      out.write("                                        <td>Nữ</td>\r\n");
      out.write("                                        <td>01653987445</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>123 Khu phố 6 - Linh Trung - Thủ Đức - HCM</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>khuonghaichau@gmail.com</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>Đang hoạt động</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td><input type=button value = \"Gửi mail cảnh báo\"></td>\r\n");
      out.write("                                    </tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("                                        <td>KH0001</td>\r\n");
      out.write("                                        <td>Khương Hải Châu</td>\r\n");
      out.write("                                        <td>Nữ</td>\r\n");
      out.write("                                        <td>01653987445</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>123 Khu phố 6 - Linh Trung - Thủ Đức - HCM</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>khuonghaichau@gmail.com</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>Đang hoạt động</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td><input type=button value = \"Gửi mail cảnh báo\"></td>\r\n");
      out.write("                                    </tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("                                        <td>KH0001</td>\r\n");
      out.write("                                        <td>Khương Hải Châu</td>\r\n");
      out.write("                                        <td>Nữ</td>\r\n");
      out.write("                                        <td>01653987445</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>123 Khu phố 6 - Linh Trung - Thủ Đức - HCM</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>khuonghaichau@gmail.com</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>Đang hoạt động</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td><input type=button value = \"Gửi mail cảnh báo\"></td>\r\n");
      out.write("                                    </tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("                                        <td>KH0001</td>\r\n");
      out.write("                                        <td>Khương Hải Châu</td>\r\n");
      out.write("                                        <td>Nữ</td>\r\n");
      out.write("                                        <td>01653987445</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>123 Khu phố 6 - Linh Trung - Thủ Đức - HCM</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>khuonghaichau@gmail.com</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>Đang hoạt động</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td><input type=button value = \"Gửi mail cảnh báo\"></td>\r\n");
      out.write("                                    </tr>\r\n");
      out.write("                                </tbody>\r\n");
      out.write("                            </table>\r\n");
      out.write("                        </div>\r\n");
      out.write("                <!-- /.row -->\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- /.container-fluid -->\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- /#page-wrapper -->\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- /#wrapper -->\r\n");
      out.write("\r\n");
      out.write("    <!-- jQuery Version 1.11.0 -->\r\n");
      out.write("    <script src=\"js/jquery-1.11.0.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <!-- Bootstrap Core JavaScript -->\r\n");
      out.write("    <script src=\"js/bootstrap.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
