package tuan10;

public class TestListSort {
	public static void main(String[] args) {
		long start = 0, stop = 0, elapsed = 0;
		ListSort<Integer> listInt = new ListSort<>();
		ListSort<Double> listDou = new ListSort<>();
		ListSort<String> listStr = new ListSort<>();
		ListSort<Character> listCha = new ListSort<>();
		
		System.out.println(
				"=====bubble Sort=====\n" + "-----------Integer-----------\n" + "Kiem tra danh sach lien ket co rong khong: ");
		System.out.print(listInt.isEmpty() ? "=>danh sach lien ket trong\n" : "=>danh sach lien ket khong trong\n");
		System.out.print("them phan tu vao danh sach lien ket\n");
		listInt.add(-10);
		listInt.add(10000);
		listInt.add(10);
		listInt.add(1000);
		listInt.add(1);
		listInt.addFirst(100);
		System.out.print(listInt.isEmpty() ? "=>danh sach lien ket trong\n" : "=>danh sach lien ket khong trong\n");
		System.out.print("In ra danh sach lien ket ban dau: \n" + listInt.toString());
		start = System.nanoTime();
		listInt.bubbleSort();
		stop = System.nanoTime();
		System.out.println("\nIn ra danh sach lien ket da xep: \n" + listInt.toString());
		elapsed = stop - start;		
		System.out.println("Thoi gian sap xep bubble sort la: " + elapsed + " nanoseconds." + "\nXoa danh sach lien ket tren: ");
		listInt.clear();
		System.out.print(listInt.isEmpty() ? "=>danh sach lien ket trong\n" : "=>danh sach lien ket khong trong\n");
		start = 0; stop = 0; elapsed = 0;
		////////////////////////////////////
		System.out.println("-----------Double-----------\n" + "Kiem tra danh sach lien ket co rong khong: ");
		System.out.print(listDou.isEmpty() ? "=>danh sach lien ket trong\n" : "=>danh sach lien ket khong trong\n");
		System.out.print("them phan tu vao danh sach lien ket\n");
		listDou.add(-10.2);
		listDou.add(10000.09279);
		listDou.add(10.12);
		listDou.add(1000.152312);
		listDou.add(1.1726);
		listDou.addFirst(100.0);
		System.out.print(listDou.isEmpty() ? "=>danh sach lien ket trong\n" : "=>danh sach lien ket khong trong\n");
		System.out.print("In ra danh sach lien ket ban dau: \n" + listDou.toString());
		start = System.nanoTime();
		listDou.bubbleSort();
		stop = System.nanoTime();
		System.out.println("\nIn ra danh sach lien ket da xep: \n" + listDou.toString());
		elapsed = stop - start;
		System.out.println("Thoi gian sap xep bubble sort la: " + elapsed + " nanoseconds." + "\nXoa danh sach lien ket tren: ");
		listDou.clear();
		System.out.print(listDou.isEmpty() ? "=>danh sach lien ket trong\n" : "=>danh sach lien ket khong trong\n");
		start = 0; stop = 0; elapsed = 0;
		////////////////////////////////////
		System.out.println("-----------String-----------\n" + "Kiem tra danh sach lien ket co rong khong: ");
		System.out.print(listStr.isEmpty() ? "=>danh sach lien ket trong\n" : "=>danh sach lien ket khong trong\n");
		System.out.print("them phan tu vao danh sach lien ket\n");
		listStr.add("Hoang");
		listStr.add("Trinh");
		listStr.add("Vo");
		listStr.add("Toan");
		listStr.add("Huy");
		listStr.addFirst("Thang");
		System.out.print(listStr.isEmpty() ? "=>danh sach lien ket trong\n" : "=>danh sach lien ket khong trong\n");
		System.out.print("In ra danh sach lien ket ban dau: \n" + listStr.toString());
		start = System.nanoTime();
		listStr.bubbleSort();
		stop = System.nanoTime();
		System.out.println("\nIn ra danh sach lien ket da xep: \n" + listStr.toString());
		elapsed = stop - start;
		System.out.println("Thoi gian sap xep bubble sort la: " + elapsed + " nanoseconds." + "\nXoa danh sach lien ket tren: ");
		listStr.clear();
		System.out.print(listStr.isEmpty() ? "=>danh sach lien ket trong\n" : "=>danh sach lien ket khong trong\n");
		start = 0; stop = 0; elapsed = 0;
		////////////////////////////////////
		System.out.println("-----------Character-----------\n" + "Kiem tra danh sach lien ket co rong khong: ");
		System.out.print(listCha.isEmpty() ? "=>danh sach lien ket trong\n" : "=>danh sach lien ket khong trong\n");
		System.out.print("them phan tu vao danh sach lien ket\n");
		listCha.add('A');
		listCha.add('S');
		listCha.add('s');
		listCha.add('c');
		listCha.add('a');
		listCha.addFirst('9');
		System.out.print(listCha.isEmpty() ? "=>danh sach lien ket trong\n" : "=>danh sach lien ket khong trong\n");
		System.out.print("In ra danh sach lien ket ban dau: \n" + listCha.toString());
		start = System.nanoTime();
		listCha.bubbleSort();
		stop = System.nanoTime();
		System.out.println("\nIn ra danh sach lien ket da xep: \n" + listCha.toString());
		elapsed = stop - start;
		System.out.println("Thoi gian sap xep bubble sort la: " + elapsed + " nanoseconds." + "\nXoa danh sach lien ket tren: ");
		listCha.clear();
		System.out.print(listCha.isEmpty() ? "=>danh sach lien ket trong\n" : "=>danh sach lien ket khong trong\n");
		start = 0; stop = 0; elapsed = 0;
		////////////////////////////////////
		System.out.println(
				"=====selection Sort=====\n" + "-----------Integer-----------\n" + "Kiem tra danh sach lien ket co rong khong: ");
		System.out.print(listInt.isEmpty() ? "=>danh sach lien ket trong\n" : "=>danh sach lien ket khong trong\n");
		System.out.print("them phan tu vao danh sach lien ket\n");
		listInt.add(-10);
		listInt.add(10000);
		listInt.add(10);
		listInt.add(1000);
		listInt.add(1);
		listInt.addFirst(100);
		System.out.print(listInt.isEmpty() ? "=>danh sach lien ket trong\n" : "=>danh sach lien ket khong trong\n");
		System.out.print("In ra danh sach lien ket ban dau: \n" + listInt.toString());
		start = System.nanoTime();
		listInt.selectionSort();
		stop = System.nanoTime();
		System.out.println("\nIn ra danh sach lien ket da xep: \n" + listInt.toString());
		elapsed = stop - start;		
		System.out.println("Thoi gian sap xep bubble sort la: " + elapsed + " nanoseconds." + "\nXoa danh sach lien ket tren: ");
		listInt.clear();
		System.out.print(listInt.isEmpty() ? "=>danh sach lien ket trong\n" : "=>danh sach lien ket khong trong\n");
		start = 0; stop = 0; elapsed = 0;
		////////////////////////////////////
		System.out.println("-----------Double-----------\n" + "Kiem tra danh sach lien ket co rong khong: ");
		System.out.print(listDou.isEmpty() ? "=>danh sach lien ket trong\n" : "=>danh sach lien ket khong trong\n");
		System.out.print("them phan tu vao danh sach lien ket\n");
		listDou.add(-10.2);
		listDou.add(10000.09279);
		listDou.add(10.12);
		listDou.add(1000.152312);
		listDou.add(1.1726);
		listDou.addFirst(100.0);
		System.out.print(listDou.isEmpty() ? "=>danh sach lien ket trong\n" : "=>danh sach lien ket khong trong\n");
		System.out.print("In ra danh sach lien ket ban dau: \n" + listDou.toString());
		start = System.nanoTime();
		listDou.selectionSort();
		stop = System.nanoTime();
		System.out.println("\nIn ra danh sach lien ket da xep: \n" + listDou.toString());
		elapsed = stop - start;
		System.out.println("Thoi gian sap xep bubble sort la: " + elapsed + " nanoseconds." + "\nXoa danh sach lien ket tren: ");
		listDou.clear();
		System.out.print(listDou.isEmpty() ? "=>danh sach lien ket trong\n" : "=>danh sach lien ket khong trong\n");
		start = 0; stop = 0; elapsed = 0;
		////////////////////////////////////
		System.out.println("-----------String-----------\n" + "Kiem tra danh sach lien ket co rong khong: ");
		System.out.print(listStr.isEmpty() ? "=>danh sach lien ket trong\n" : "=>danh sach lien ket khong trong\n");
		System.out.print("them phan tu vao danh sach lien ket\n");
		listStr.add("Hoang");
		listStr.add("Trinh");
		listStr.add("Vo");
		listStr.add("Toan");
		listStr.add("Huy");
		listStr.addFirst("Thang");
		System.out.print(listStr.isEmpty() ? "=>danh sach lien ket trong\n" : "=>danh sach lien ket khong trong\n");
		System.out.print("In ra danh sach lien ket ban dau: \n" + listStr.toString());
		start = System.nanoTime();
		listStr.selectionSort();
		stop = System.nanoTime();
		System.out.println("\nIn ra danh sach lien ket da xep: \n" + listStr.toString());
		elapsed = stop - start;
		System.out.println("Thoi gian sap xep bubble sort la: " + elapsed + " nanoseconds." + "\nXoa danh sach lien ket tren: ");
		listStr.clear();
		System.out.print(listStr.isEmpty() ? "=>danh sach lien ket trong\n" : "=>danh sach lien ket khong trong\n");
		start = 0; stop = 0; elapsed = 0;
		////////////////////////////////////
		System.out.println("-----------Character-----------\n" + "Kiem tra danh sach lien ket co rong khong: ");
		System.out.print(listCha.isEmpty() ? "=>danh sach lien ket trong\n" : "=>danh sach lien ket khong trong\n");
		System.out.print("them phan tu vao danh sach lien ket\n");
		listCha.add('A');
		listCha.add('S');
		listCha.add('s');
		listCha.add('c');
		listCha.add('a');
		listCha.addFirst('9');
		System.out.print(listCha.isEmpty() ? "=>danh sach lien ket trong\n" : "=>danh sach lien ket khong trong\n");
		System.out.print("In ra danh sach lien ket ban dau: \n" + listCha.toString());
		start = System.nanoTime();
		listCha.selectionSort();
		stop = System.nanoTime();
		System.out.println("\nIn ra danh sach lien ket da xep: \n" + listCha.toString());
		elapsed = stop - start;
		System.out.println("Thoi gian sap xep bubble sort la: " + elapsed + " nanoseconds." + "\nXoa danh sach lien ket tren: ");
		listCha.clear();
		System.out.print(listCha.isEmpty() ? "=>danh sach lien ket trong\n" : "=>danh sach lien ket khong trong\n");
		start = 0; stop = 0; elapsed = 0;
		////////////////////////////////////
	}
}
