package lab9;

public class Bai1 {
	public static void main(String[] args) {
		ArraySet<Integer> mangInt0 = new ArraySet<>();
		ArraySet<Integer> mangInt1 = new ArraySet<>();
		ArraySet<Integer> mangInt2 = new ArraySet<>();
		ArraySet<String> mangStr0 = new ArraySet<>();
		ArraySet<String> mangStr1 = new ArraySet<>();
		ArraySet<String> mangStr2 = new ArraySet<>();
		ArraySet<Double> mangDou0 = new ArraySet<>();
		ArraySet<Double> mangDou1 = new ArraySet<>();
		ArraySet<Double> mangDou2 = new ArraySet<>();
		//////////////////////////////////////////////////
		System.out.println("------Array------" + "\n======Integer=====");
		System.out.print(mangInt0.isEmpty() ? "=>mang rong\n" : "=>mang ko rong\n");
		System.out.print("Them vao phan tu vao mang 1\n");
		mangInt0.add(18);
		mangInt0.add(20);
		System.out.print(mangInt0.isEmpty() ? "=>mang rong\n" : "=>mang ko rong\n");
		System.out.print("Size mang 1: " + mangInt0.size() + "\nIn mang 1: \n" + mangInt0.toString());
		mangInt1.add(10);
		mangInt1.add(11);
		mangInt1.add(12);
		mangInt1.add(13);
		mangInt1.add(14);
		mangInt1.add(15);
		System.out.print(mangInt1.isEmpty() ? "=>mang rong\n" : "=>mang ko rong\n");
		System.out.println("Them phan tu vao mang 2" + " In mang 2: \n" + mangInt1.toString());
		mangInt0.addAll(mangInt1);
		System.out.println("In mang 1 sau khi addAll mang 2: \n" + mangInt0.toString());
		mangInt0.add(25);
		mangInt0.add(26);
		System.out.println("In mang 1 sau khi them phan tu: \n" + mangInt0.toString());
		mangInt2.add(9);
		mangInt2.addAll(mangInt0);
		mangInt2.add(21);
		mangInt2.add(22);
		mangInt2.add(23);
		System.out.println("In mang 3: \n" + mangInt2.toString());
		mangInt2.union(mangInt0);
		System.out.println("In mang 3 sau khi union: \n" + mangInt2.toString());
		mangInt0.addAll(mangInt2);
		mangInt0.remove(10);
		System.out.println("In mang 1: \n" + mangInt0.toString() + "\nSize mang 1: " + mangInt0.size());
		mangInt0.removeRandom();
		System.out.println("In mang 1: \n" + mangInt0.toString());
		System.out.println("In mang 2: \n" + mangInt1.toString());
		System.out.println("In mang 3: \n" + mangInt2.toString());
		System.out.println("difference: " + mangInt1.difference(mangInt0));
		System.out.println("In mang 1: \n" + mangInt0.toString());
		System.out.println("In mang 3: \n" + mangInt2.toString());
		System.out.println("In mang 1: \n" + mangInt0.toString());
		mangInt1.add(8);
		mangInt1.add(1);
		System.out.println("difference: " + mangInt0.difference(mangInt1));
		System.out.println("In mang 1: \n" + mangInt0.toString());
		System.out.println("In mang 2: \n" + mangInt1.toString());
		//////////////////////////////////////////////////////////
		System.out.println("======String=====");
		System.out.print(mangStr0.isEmpty() ? "=>mang rong\n" : "=>mang ko rong\n");
		System.out.print("Them vao phan tu vao mang 1\n");
		mangStr0.add("A");
		mangStr0.add("S");
		System.out.print(mangStr0.isEmpty() ? "=>mang rong\n" : "=>mang ko rong\n");
		System.out.println("Size mang 1: " + mangStr0.size() + "\nIn mang 1: \n" + mangStr0.toString());
		mangStr1.add("W");
		mangStr1.add("K");
		mangStr1.add("Q");
		mangStr1.add("F");
		mangStr1.add("G");
		mangStr1.add("X");
		System.out.print(mangStr1.isEmpty() ? "=>mang rong\n" : "=>mang ko rong\n");
		System.out.println("Them phan tu vao mang 2" + " In mang 2: \n" + mangStr1.toString());
		mangStr0.addAll(mangStr1);
		System.out.println("In mang 1 sau khi addAll mang 2: \n" + mangStr0.toString());
		mangStr0.add("I");
		mangStr0.add("T");
		System.out.println("In mang 1 sau khi them phan tu: \n" + mangStr0.toString());
		mangStr2.add("D");
		mangStr2.addAll(mangStr0);
		mangStr2.add("V");
		mangStr2.add("S");
		mangStr2.add("C");
		System.out.println("In mang 3: \n" + mangStr2.toString());
		mangStr2.union(mangStr0);
		System.out.println("In mang 3 sau khi union: \n" + mangStr2.toString());
		mangStr0.addAll(mangStr2);
		mangStr0.remove("A");
		System.out.println("In mang 1: \n" + mangStr0.toString() + "\nSize mang 1: " + mangStr0.size());
		mangStr0.removeRandom();
		System.out.println("In mang 1: \n" + mangStr0.toString());
		System.out.println("In mang 2: \n" + mangStr1.toString());
		System.out.println("In mang 3: \n" + mangStr2.toString());
		System.out.println("difference: " + mangStr1.difference(mangStr0));
		System.out.println("In mang 1: \n" + mangStr0.toString());
		System.out.println("In mang 3: \n" + mangStr2.toString());
		System.out.println("In mang 1: \n" + mangStr0.toString());
		mangStr1.add("S");
		mangStr1.add("Z");
		System.out.println("difference: " + mangStr0.difference(mangStr1));
		System.out.println("In mang 1: \n" + mangStr0.toString());
		System.out.println("In mang 2: \n" + mangStr1.toString());
		//////////////////////////////////////////////////////////
		System.out.println("=====Double=====");
		System.out.print(mangDou0.isEmpty() ? "=>mang rong\n" : "=>mang ko rong\n");
		System.out.print("Them vao phan tu vao mang 1\n");
		mangDou0.add(1.8);
		mangDou0.add(2.0);
		System.out.print(mangDou0.isEmpty() ? "=>mang rong\n" : "=>mang ko rong\n");
		System.out.print("Size mang 1: " + mangDou0.size() + "\nIn mang 1: \n" + mangDou0.toString());
		mangDou1.add(1.0);
		mangDou1.add(1.1);
		mangDou1.add(1.2);
		mangDou1.add(1.3);
		mangDou1.add(1.4);
		mangDou1.add(1.5);
		System.out.print(mangDou1.isEmpty() ? "=>mang rong\n" : "=>mang ko rong\n");
		System.out.println("Them phan tu vao mang 2" + " In mang 2: \n" + mangDou1.toString());
		mangDou0.addAll(mangDou1);
		System.out.println("In mang 1 sau khi addAll mang 2: \n" + mangDou0.toString());
		mangDou0.add(2.5);
		mangDou0.add(2.6);
		System.out.println("In mang 1 sau khi them phan tu: \n" + mangDou0.toString());
		mangDou2.add(0.9);
		mangDou2.addAll(mangDou0);
		mangDou2.add(2.1);
		mangDou2.add(2.2);
		mangDou2.add(2.3);
		System.out.println("In mang 3: \n" + mangDou2.toString());
		mangDou2.union(mangDou0);
		System.out.println("In mang 3 sau khi union: \n" + mangDou2.toString());
		mangDou0.addAll(mangDou2);
		mangDou0.remove(1.0);
		System.out.println("In mang 1: \n" + mangDou0.toString() + "\nSize mang 1: " + mangDou0.size());
		mangDou0.removeRandom();
		System.out.println("In mang 1: \n" + mangDou0.toString());
		System.out.println("In mang 2: \n" + mangDou1.toString());
		System.out.println("In mang 3: \n" + mangDou2.toString());
		System.out.println("difference: " + mangDou1.difference(mangDou0));
		System.out.println("In mang 1: \n" + mangDou0.toString());
		System.out.println("In mang 3: \n" + mangDou2.toString());
		System.out.println("In mang 1: \n" + mangDou0.toString());
		mangDou1.add(0.8);
		mangDou1.add(0.1);
		System.out.println("difference: " + mangDou0.difference(mangDou1));
		System.out.println("In mang 1: \n" + mangDou0.toString());
		System.out.println("In mang 2: \n" + mangDou1.toString());
	}

}
